routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('locale/{locale}', function ($locale) {
    session(['locale' =>  $locale]);
    session()->keep('success');   
    return redirect()->back();
});

Route::get('/', function () {
    return redirect('/dashboard');
});

Auth::routes(['verify' => true]);

Route::middleware('admin_role')->group(function () {
	Route::resource('users', 'UserController', ['names' => 'users']);
	Route::resource('article_categories', 'ArticleCategoryController', ['names' => 'article_categories']);
	Route::resource('push_messages', 'PushMessageController', ['names' => 'push_messages']);
});

Route::middleware('verified','user_role',)->group(function () {
	Route::get('/dashboard', 'UserDashboardController@index')->name('user_dashboard');
	Route::resource('customers', 'CustomerController', ['names' => 'customers']);
	Route::resource('articles', 'ArticleController', ['names' => 'articles']);
	Route::resource('offers', 'OfferController', ['names' => 'offers']);
	Route::resource('invoices', 'InvoiceController', ['names' => 'invoices']);
	Route::resource('user-settings', 'UserSettingsController', ['names' => 'user-settings']);
	Route::resource('offer-invoice-settings', 'OfferInvoiceSettingsController', ['names' => 'offer-invoice-settings']);
	Route::post('get-article-data/{id}','OfferController@getArticleData');
	Route::get('/help', 'UserHelpController@index')->name('help');
});

app/ArticleCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ArticleCategory extends Model
{
    use HasFactory;

    protected $fillable = [
    	'category_name', 'category_id', 'category_parent_id'
    ];

    public function article()
    {
    	return $this->hasMany('App\Article');
    }
}

app/Http/Controllers/ArticleCategoryController.php
<?php

namespace App\Http\Controllers;

use App\ArticleCategory;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Article;

class ArticleCategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $article_categories = ArticleCategory::all();
        return view ('article_categories.index', compact('article_categories'));
    }

    public function create()
    {
        $next_id = ArticleCategory::max('category_id') + 1;
        return view('article_categories.create', compact('next_id'));
    }

    public function store(Request $request)
    {
        $attributes = $this->validateCategory(null);
        $article_category = ArticleCategory::create($attributes);

        return redirect ('/article_categories')->with('success', __('article_categories.article_category_added') ); 
    }

    public function edit(ArticleCategory $articleCategory)
    {
        $count = Article::where('category', $articleCategory->category_id)->count();
        return view('article_categories.edit', compact('articleCategory', 'count'));
    }

    public function update(Request $request, ArticleCategory $articleCategory)
    {
        $attributes = $this->validateCategory($articleCategory);
        $articleCategory->update($attributes);

        return redirect ('/article_categories')->with('success', __('article_categories.category_updated') ); 
    }

     public function destroy(ArticleCategory $articleCategory)
    {
        $articleCategory->delete();

        return redirect ('/article_categories')->with('success', __('article_categories.category_deleted') );
    }

    protected function validateCategory($articleCategory)
    {	
    	$ids = $this->getAllowedIds();
		$ids = implode(',', $ids);

        return request()->validate([
            'category_name' => ['required','string','min:1','max:100','unique:article_categories'],
            'category_id' => [
            	'required',
            	'numeric',
            	Rule::unique('article_categories')->ignore($articleCategory->category_id, 'category_id')
            ],
            'category_parent_id' => ['required', 'in:'.$ids,'numeric']
        ]);
    }

    protected function getAllowedIds() //Get all existing category IDs, plus root (zero) ID
    {
    	$category_parents_ids = array(0);
		if(ArticleCategory::pluck('category_id')->count()) {
			$category_parents_ids = ArticleCategory::pluck('category_id')->unique()->toArray();
			array_push($category_parents_ids, 0);
		}

		return $category_parents_ids;
    }
}

resources/views/article_categories/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('article_categories.add_category') }}</h1>
    </div>
	<div class="container-fluid">
        <form method="POST" action="{{ route('article_categories.store') }}" enctype="multipart/form-data">
        @csrf
			<div class="row">
        		<div class="col-sm-3">
				    <div class="form-group">
				        <label for="category_name">{{ __('article_categories.category_name') }}</label> 
				        <input id="category_name" type="text" class="form-control @error('category_name') is-invalid @enderror" name="category_name" value="{{ old('category_name') }}" autofocus required="required">
				        @error('category_name')
				           	<span class="invalid-feedback" role="alert">
				            	<strong>{{ $message }}</strong>
				            </span>
				        @enderror
				    </div>
			    </div>
			</div>
			<div class="row">
        		<div class="col-sm-3">
				    <div class="form-group">
				        <label for="category_id">{{ __('article_categories.category_id') }}</label> 
				        <input id="category_id" type="text" class="form-control @error('category_id') is-invalid @enderror" name="category_id" value="{{ $next_id }}" autofocus required="required">
				        @error('category_id')
				           	<span class="invalid-feedback" role="alert">
				            	<strong>{{ $message }}</strong>
				            </span>
				        @enderror
				    </div>
			    </div>
			</div>
			<div class="row">
        		<div class="col-sm-3">
				    <div class="form-group">
				        <label for="category_parent_id">{{ __('article_categories.category_parent_id') }}</label> 
				        <input id="category_parent_id" type="text" class="form-control @error('category_parent_id') is-invalid @enderror" name="category_parent_id" value="{{ old('category_parent_id') }}" autofocus required="required">
				        @error('category_parent_id')
				           	<span class="invalid-feedback" role="alert">
				            	<strong>{{ $message }}</strong>
				            </span>
				        @enderror
				    </div>
			    </div>
			</div>
		    <div class="modal-footer">
				<button type="button" class="btn btn-secondary pull-left" onclick="window.location.href='{{ route('article_categories.index')}}'">{{ __('buttons.back') }}</button>
				<button type="submit" class="btn btn-primary">{{ __('buttons.save') }}</button>
			</div>
		</form>
	</div>
@endsection

resources/views/article_categories/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('article_categories.edit_category') }}</h1>
    </div>
	<div class="container-fluid">
        <form method="POST" action="{{ route('article_categories.update', $articleCategory->id) }}" enctype="multipart/form-data">
        @method('PATCH')
        @csrf
			<div class="row">
        		<div class="col-sm-3">
				    <div class="form-group">
				        <label for="category_name">{{ __('article_categories.category_name') }}</label> 
				        <input id="category_name" type="text" class="form-control @error('category_name') is-invalid @enderror" name="category_name" value="{{ $articleCategory->category_name }}" autofocus required="required">
				        @error('category_name')
				           	<span class="invalid-feedback" role="alert">
				            	<strong>{{ $message }}</strong>
				            </span>
				        @enderror
				    </div>
			    </div>
			</div>
			<div class="row">
        		<div class="col-sm-3">
				    <div class="form-group">
				        <label for="category_id">{{ __('article_categories.category_id') }}</label> 
				        <input id="category_id" type="text" class="form-control @error('category_id') is-invalid @enderror" name="category_id" value="{{ $articleCategory->category_id }}" required="required">
				        @error('category_id')
				           	<span class="invalid-feedback" role="alert">
				            	<strong>{{ $message }}</strong>
				            </span>
				        @enderror
				    </div>
			    </div>
			</div>
			<div class="row">
        		<div class="col-sm-3">
				    <div class="form-group">
				        <label for="category_parent_id">{{ __('article_categories.category_parent_id') }}</label> 
				        <input id="category_parent_id" type="text" class="form-control @error('category_parent_id') is-invalid @enderror" name="category_parent_id" value="{{ $articleCategory->category_parent_id }}" required="required">
				        @error('category_parent_id')
				           	<span class="invalid-feedback" role="alert">
				            	<strong>{{ $message }}</strong>
				            </span>
				        @enderror
				    </div>
			    </div>
			</div>
			<div class="row">
				<div class="col-sm-auto">
					<p @if($count) style="color:red" @endif> Aticles with this category ID: {{ $count }} </p>
				</div>
			</div>
		    <div class="modal-footer">
				<button type="button" class="btn btn-secondary pull-left" onclick="window.location.href='{{ route('article_categories.index')}}'">{{ __('buttons.back') }}</button>
				<button type="submit" class="btn btn-primary">{{ __('buttons.save') }}</button>
			</div>
		</form>
	</div>
@endsection

resources/views/article_categories/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('article_categories.article_categories') }}</h1>
    </div>
    <div class="">
        <button type="button" class="btn btn-primary text-nowrap" onclick="location.href='{{ route('article_categories.create') }}'" style="float:right; margin-bottom: 0.5em;">
            {{ __('article_categories.add_category') }}
        </button>
    </div>
    @if(!$article_categories->count())
        <p>{{ __('article_categories.no_article_categories') }}</p>
    @else
    <div class="table-responsive">
        <table id="article_categories-table" class="table">
            <thead>
                <tr>
                    <th>{{ __('article_categories.category_name') }}</th>
                    <th>{{ __('article_categories.category_id') }}</th>
                    <th>{{ __('article_categories.category_parent_id') }}</th>
                    <th></th>       
                </tr>
            </thead>
            <tbody>
                @foreach($article_categories as $category)
                <tr>
                    <td> {{ $category->category_name }}</td>
                    <td> {{ $category->category_id }} </td>
                    <td> {{ $category->category_parent_id }} </td>
                    <td>
                        <a href="{{ route('article_categories.edit', $category->id) }}">
                            <span class="feather-icons" data-feather="edit"></span>
                        </a>
                        <a href="#" data-toggle="modal" data-target="#confirm-delete-modal" data-url="{{ route('article_categories.destroy', $category->id) }}">
                            <span class="feather-icons" data-feather="trash-2"></span>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif
    @include('../common/confirm-delete-modal')
    <script>
        
        $('#confirm-delete-modal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            const url = button.data('url');
            $('#deleteFormClient').attr('action', url);
        });

        $(".alert.alert-success").fadeTo(4000, 500).slideUp(500, function(){
            $(".alert.alert-success").slideUp(500);
        });

    </script>
@endsection