routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('locale/{locale}', function ($locale) {
    session(['locale' =>  $locale]);
    session()->keep('success');   
    return redirect()->back();
});

Route::get('/', function () {
    return redirect('/dashboard');
});

Auth::routes(['verify' => true]);

Route::middleware('admin_role')->group(function () {
	Route::resource('users', 'UserController', ['names' => 'users']);
	Route::resource('article_categories', 'ArticleCategoryController', ['names' => 'article_categories']);
	Route::resource('push_messages', 'PushMessageController', ['names' => 'push_messages']);
});

Route::middleware('verified','user_role',)->group(function () {
	Route::get('/dashboard', 'UserDashboardController@index')->name('user_dashboard');
	Route::resource('customers', 'CustomerController', ['names' => 'customers']);
	Route::resource('articles', 'ArticleController', ['names' => 'articles']);
	Route::resource('offers', 'OfferController', ['names' => 'offers']);
	Route::resource('invoices', 'InvoiceController', ['names' => 'invoices']);
	Route::resource('user-settings', 'UserSettingsController', ['names' => 'user-settings']);
	Route::resource('offer-invoice-settings', 'OfferInvoiceSettingsController', ['names' => 'offer-invoice-settings']);
	Route::post('get-article-data/{id}','OfferController@getArticleData');
	Route::get('/help', 'UserHelpController@index')->name('help');
});

app/Offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    protected $fillable = [
    	'user_id', 'offer_number', 'customer_id', 'offer_date', 'offer_expire_date',
        'total', 'discount', 'tax', 'tax_value', 'grand_total', 'pdf_file'
    ];

    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    public function customer()
    {
    	return $this->belongsTo('App\Customer');
    }

    public function invoice()
    {
        return $this->hasOne('App\Invoice');
    }

    public function articles()
    {
    	return $this->hasMany('App\OfferArticle');
    }
}

app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use App\Offer;
use App\User;
use App\Article;
use App\OfferArticle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Arr;

class OfferController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth');
    }

    public function index()
    {
        $user = User::findOrFail(Auth::user()->id);
        $offers = $user->offers;
        
        return view('offers.index', compact('offers'));
    }

    public function create()
    {
        $user = User::findOrFail(Auth::user()->id);
        $customers = $user->customers;
        if(!$customers->count())
            return back()->with('error', __('offers.no_customers'));
        $offer_number = $this->generateOfferNumber();
        $articles = Article::all();

        return view('offers.create', compact('customers', 'offer_number', 'articles'));
    }

    public function store(Request $request)
    {
        $attributes = $this->validateOffer($current_offer_number = null);
        $attributes['user_id'] = Auth::user()->id;
        $attributes['total'] = 0;
        $attributes['discount'] = 0;
        (request('tax-free-offer') === 'true') ? 
            $attributes['tax'] = 0 : $attributes['tax'] = 20;
        $attributes['pdf_file'] = 'Offer_' . time() . '.pdf';

        //Calculate sum for offer
        $articles = json_decode($attributes['articleslist'], true);
        foreach ($articles as $article) {
            $attributes['total'] += $article['total'];
        }
        $attributes['total'] = number_format((float)$attributes['total'], 2, '.', '');
        $attributes['tax_value'] = ($attributes['total'] * ($attributes['tax']/100));
        $attributes['tax_value'] = number_format((float)$attributes['tax_value'], 2, '.', '');
        $attributes['grand_total'] = $attributes['total'] + $attributes['tax_value'];
        $attributes['grand_total'] = number_format((float)$attributes['grand_total'], 2, '.', '');

        //Create offer
        $offer = Offer::create($attributes);

        //Add fields for articles which are not created automatically
        $articles = collect($articles)->map(function ($item) use($offer) {
            $item['offer_id'] = $offer->id;
            $item['created_at'] = now()->toDateString();
            $item['updated_at'] = now()->toDateString();
            return $item;
        });

        //Insert articles
        OfferArticle::insert($articles->toArray());

        //Generate PDF
        $user_settings = Auth::user()->user_settings;
        $pdf = PDF::loadView('common.templates.offer_template1', compact('offer', 'articles', 'user_settings'));
        //return $pdf->stream();
        $pdf->save(storage_path() .'/app/public/offers/' . $attributes['pdf_file']);
        
        return redirect ('/offers')->with('success', __('offers.offer_added'));
    }

    public function show(Offer $offer)
    {
        abort_if(Gate::denies('update', $offer), 404);
        if(!Storage::exists('offers/' . $offer->pdf_file)) 
            return redirect('/offers/' . $offer->id . '/edit')->with('error', __('offers.pdf_not_found'));

        return response()->file(storage_path() . '/app/public/offers/' . $offer->pdf_file);
    }

    public function edit(Offer $offer)
    {
        abort_if(Gate::denies('update', $offer) || !$offer->customer, 404);
        $customers = Auth::user()->customers;
        $articles = Article::all();
        $offer_articles = $offer->articles;
        return view('offers.edit', compact('offer', 'customers', 'articles', 'offer_articles'));
    }

    public function update(Request $request, Offer $offer)
    {
        $attributes = $this->validateOffer($current_offer_number = $offer->offer_number);
        $attributes['total'] = 0;
        $attributes['discount'] = 0;
        (request('tax-free-offer') === 'true') ? 
            $attributes['tax'] = 0 : $attributes['tax'] = 20;
        $attributes['pdf_file'] = 'Offer_' . time() . '.pdf';

        //Calculate sum for offer
        $articles = json_decode($attributes['articleslist'], true);
        foreach ($articles as $article) {
            $attributes['total'] += $article['total'];
        }
        $attributes['total'] = number_format((float)$attributes['total'], 2, '.', '');
        $attributes['tax_value'] = ($attributes['total'] * ($attributes['tax']/100));
        $attributes['tax_value'] = number_format((float)$attributes['tax_value'], 2, '.', '');
        $attributes['grand_total'] = $attributes['total'] + $attributes['tax_value'];
        $attributes['grand_total'] = number_format((float)$attributes['grand_total'], 2, '.', '');

        //Add fields for articles which are not created automatically
        $articles = collect($articles)->map(function ($item) use($offer) {
            $item['offer_id'] = $offer->id;
            $item['created_at'] = now()->toDateString();
            $item['updated_at'] = now()->toDateString();
            return $item;
        });      

        //Remove all articles for current invoice
        OfferArticle::where('offer_id', $offer->id)->delete();

        //Remove PDF file
        if(Storage::exists('offers/' . $offer->pdf_file))
            Storage::delete('offers/' . $offer->pdf_file);

        //Update offer
        $offer->update($attributes);

        //Insert new articles
        OfferArticle::insert($articles->toArray());

        //Recreate PDF file
        $user_settings = Auth::user()->user_settings;
        $pdf = PDF::loadView('common.templates.offer_template1', compact('offer', 'articles', 'user_settings'));
        $pdf->save(storage_path() .'/app/public/offers/' . $attributes['pdf_file']);
        
        return redirect ('/offers')->with('success', __('offers.offer_updated'));
    }

    public function destroy(Offer $offer)
    {
        abort_if(Gate::denies('update', $offer), 404);
        $offer->delete();

        //Remove PDF
        if(Storage::exists('offers/' . $offer->pdf_file))
            Storage::delete('offers/' . $offer->pdf_file);

        return redirect ('/offers')->with('success', __('offers.offer_deleted'));
    }

    protected function validateOffer($current_offer_number)
    {
        $user = User::findOrFail(Auth::user()->id);
        $offer_numbers = '';
        if($user->offers) {
            $offer_numbers = $user->offers->pluck('offer_number')->toArray();
            if($_SERVER['REQUEST_URI'] != '/offers') { //edit offer so we can use existing offer number as well
                $key = array_search($current_offer_number, $offer_numbers);
                $offer_numbers = Arr::except($offer_numbers, [$key]);
            }
            $offer_numbers = implode(',', $offer_numbers);
        }
        return request()->validate([
            'offer_number' => ['not_in:'.$offer_numbers,'required','string','min:8','max:15'],
            'customer_id' => ['required'],
            'offer_date' => ['required','date'],
            'offer_expire_date' => ['required', 'date','after_or_equal:start_date'],
            'articleslist' => ['required']
        ]);
    }

    protected function generateOfferNumber()
    {
        $user = User::findOrFail(Auth::user()->id);
        $prefix = ($user->offer_invoice_settings->offer_prefix) ?? 'AN';
        $delimiter = ($user->offer_invoice_settings->offer_delimiter) ?? '/';
        $suffix = ($user->offer_invoice_settings->offer_suffix) ?? date('Y');
        $offer_numbers = array();
        if($user->offers) {
            foreach($user->offers as $offer) {
            	$temp_number = substr($offer->offer_number, 2);
            	$temp_number = substr($temp_number, 0, -5);
                array_push($offer_numbers, $temp_number);
            }
        }
        if(empty($offer_numbers))
            return $prefix . '0001' . $delimiter . $suffix;
        else {
            $counter = max($offer_numbers);
            $counter++;
            switch (true) {
                case $counter < 10: 
                    $number = $prefix . '000' . $counter . $delimiter . $suffix;
                    break;
                case $counter < 100:
                    $number = $prefix . '00' . $counter . $delimiter . $suffix;
                    break;
                case $counter < 1000:
                    $number = $prefix . '0' . $counter . $delimiter . $suffix;
                    break;
                case $counter >= 1000:
                    $number = $prefix . $counter . $delimiter . $suffix;
                    break;
                default:
                    $number = $prefix . rand() . $delimiter . $suffix;
                    break;
            }
            return $number;
        }
    }

    protected function getArticleData($article_id) 
    {
        if($article_id) {
            $article = Article::findOrFail($article_id);
            $attributes['main_product_group'] = ($article->main_product_group) ?? '-';
            $attributes['price'] = ($article->price) ?? '0.00';
            $attributes['price_unit'] = ($article->price_unit) ?? '1';
            $attributes['unit'] = ($article->unit) ?? 'ST';
            $attributes['currency'] = ($article->currency) ?? 'EUR';
            $attributes['image_name'] = ($article->articleImage) ? $article->articleImage->name : 'no_image.png';
        }
       return json_encode(array('data' => $attributes));
       
    }

}

resources/views/offers/create.blade.php
@extends('layouts.user')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('offers.add_offer')}}</h1>
    </div>
    <div class="container-fluid">
        <form id="offer-form" action="{{ route('offers.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="offer_number">{{ __('offers.offer_number')}}</label> 
                        <input type="text" class="form-control @error('offer_number') is-invalid @enderror" name="offer_number" value="{{ $offer_number }}" autofocus>
                        @error('offer_number')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="customer">{{ __('offers.customer')}}</label> 
                        <select name="customer_id" class="form-control @error('customer_id') is-invalid @enderror">
                            <option value=""></option>   
                            @foreach($customers as $customer)   
                                <option type="text" name="customer"
                                    value="{{ $customer->id }}">{{ $customer->company_name ?? $customer->name }}
                                </option>
                            @endforeach
                        </select>
                        @error('customer_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="offer_date">{{ __('offers.date')}}</label> 
                        <input id="offer_date" type="date" class="form-control @error('offer_date') is-invalid @enderror" name="offer_date" value="{{ date('Y-m-d') }}" autofocus>
                        @error('offer_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="offer_expire_date">{{ __('offers.expire_date')}}</label> 
                        <input id="offer_expire_date" type="date" class="form-control @error('offer_expire_date') is-invalid @enderror" name="offer_expire_date" value="{{ date('Y-m-d') }}" autofocus>
                        @error('offer_expire_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <input id="articleslist" type="hidden" name="articleslist">
            <input id="tax-free-offer" type="hidden" name="tax-free-offer">
        </form>
        <form id="articles-fields">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group form-offer-inline-elements">
                        <label for="article">{{ __('offers.article')}}</label>
                        <select id="article_select" name="article_select" class="form-control">
                            <option></option>
                            @foreach($articles as $article)
                                <option class="form-control" name="article" value="{{ $article->id }}" title="{{ $article->price }}">
                                    {{ $article->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-offer-inline-elements">
                        <label for="price">{{ __('offers.price')}} €</label> 
                        <input id="price" type="number" class="form-control" name="price" step="0.01" min="0" value="0.00" autofocus>
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="form-group form form-offer-inline-elements">
                        <label for="quantity">{{ __('offers.quantity')}}</label> 
                        <input id="quantity" type="number" class="form-control" name="quantity" step="1" min="1" max="10000" value="1" autofocus>
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="form-group form-offer-inline-elements">
                        <label for="discount">{{ __('offers.discount')}} %</label> 
                        <input id="discount" type="number" class="form-control" name="discount" step="0.05" min="0.00" max="100" value="0.00" autofocus>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-offer-inline-elements">
                        <button type="button" class="btn btn-primary add-article">{{ __('buttons.add')}}</button>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-offer-inline-elements">
                        <button type="button" class="btn btn-primary custom-insert" data-toggle="modal" data-target="#custom-insert-modal">
                            {{ __('buttons.manual_input')}}
                        </button>
                    </div>
                </div>
            </div>
        </form>
        @include('../common/custom-insert-modal')
        @include('../common/edit-modal')
        <div class="row offer-article-image-preview">
            <div class="col-sm-auto">
                <img id="article-image-preview" src="" width="100px" height="auto">
            </div>
            <div class="col-sm-auto">
                <p id="product_group"></p>
                <p id="price_unit"></p>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table" id="offer-articles-table" name="articles">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{{ __('offers.article')}}</th>
                        <th>{{ __('offers.price')}} €</th>
                        <th>{{ __('offers.quantity')}}</th>
                        <th>{{ __('offers.discount')}} %</th>
                        <th>{{ __('offers.total')}}</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6"></td>
                        <td>
                            <span>{{ __('offers.total')}}</span>
                            <span id="total">0.00</span>
                            <span>€</span>
                        </td>
                    </tr>
                    <tr class="offer-tax-total">
                        <td colspan="6"></td>
                        <td>
                            <span>{{ __('offers.tax')}}</span>
                            <span class="tax-20">20%</span>
                            <span id="tax">0.00</span>
                            <span>€</span>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6"></td>
                        <td>
                            <span>{{ __('offers.grand_total')}}</span>
                            <span id="grandTotal">0.00</span>                
                            <span>€</span>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="offer-buttons">
            <div class="row">
                <div class="col">
                    <input type="checkbox" id="tax-free" name="tax-free"> {{ __('offers.tax_free_note') }}
                </div>
                <div class="col-auto">
                    <button type="button" class="btn btn-secondary" onclick="window.location.href='{{ route('offers.index')}}'">
                        {{ __('buttons.back')}}
                    </button>
                    <button id="submit-offer-button" type="submit" class="btn btn-success btn-save">
                        {{ __('buttons.save')}}
                    </button>
                </div> 
            </div>
        </div>
    </div>
<script src="{{ asset('js/offerHelpers.js') }}"></script>

<script>
    $(document).ready(function() {
        $('#article_select').select2({
            placeholder: "{{ __('offers.select_article') }}",
            theme: "bootstrap4"
        }).on('change', function(){
            var optionPrice = $('option:selected', this).attr('title');
            $('#price').val(optionPrice);
        });
    });
</script>

@endsection

resources/views/offers/index.blade.php
@extends('layouts.user')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('offers.offers') }}</h1>
    </div>
    <div class="">
        <button type="button" class="btn btn-primary text-nowrap" onclick="location.href='{{ route('offers.create') }}'" style="float:right; margin-bottom: 0.5em;">
            {{ __('offers.add_offer') }}
        </button>
    </div>
    @if(!$offers->count())
        <p>{{ __('offers.no_offers') }}</p>
    @else
        <table id="offers-table" class="display responsive nowrap" width="100%">
            <thead>
                <tr>
                    <th>{{ __('offers.offer_number') }}</th>
                    <th>{{ __('offers.customer') }}</th>
                    <th>{{ __('offers.date') }}</th>
                    <th>{{ __('offers.expire_date') }}</th>
                    <th>{{ __('offers.total') }}</th>
                    <th>{{ __('offers.discount') }}</th>
                    <th>{{ __('offers.grand_total') }}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach($offers as $offer)
            <tr>
                <td> {{ $offer->offer_number }} </td>
                @if($offer->customer)
                    <td> {{ $offer->customer->company_name ?? $offer->customer->name }} </td>
                @else
                    <td> - </td>
                @endif
                <td> {{ $offer->offer_date }} </td>
                <td> {{ $offer->offer_expire_date }} </td>
                <td> {{ $offer->total }} </td>
                <td> {{ $offer->discount }} </td>
                <td> {{ $offer->grand_total }} </td>
                <td> 
                    <a href="{{ route('offers.show', $offer->id) }}" target="_blank">
                        <span class="feather-icons" data-feather="eye"></span>
                    </a>
                    @if($offer->customer)
                        <a href="{{ route('offers.edit', $offer->id) }}">
                            <span class="feather-icons" data-feather="edit"></span>
                        </a>
                    @endif
                    <a href="#" data-toggle="modal" data-target="#confirm-delete-modal" data-url="{{ route('offers.destroy', $offer->id) }}">
                        <span class="feather-icons" data-feather="trash-2"></span>
                    </a>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    @endif
    @include('../common/confirm-delete-modal')
    <script>
        $(document).ready( function () {
            var input = {
                stateSave: true,
                responsive: {
                    details: false
                },
                columnDefs: [
                    { responsivePriority: 1, targets: 0 },
                    { responsivePriority: 1, targets: 7 }
                ]
            }; 
            if($('html')[0].lang == 'de') {
                input.language ={url: '/js/localization/dataTables_de.json'};
            }
            $('#offers-table').DataTable(input);
        });

        $('#confirm-delete-modal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            const url = button.data('url');
            $('#deleteFormClient').attr('action', url);
        });

        $(".alert.alert-success").fadeTo(4000, 500).slideUp(500, function(){
            $(".alert.alert-success").slideUp(500);
        });
    </script>

@endsection