routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('locale/{locale}', function ($locale) {
    session(['locale' =>  $locale]);
    session()->keep('success');   
    return redirect()->back();
});

Route::get('/', function () {
    return redirect('/dashboard');
});

Auth::routes(['verify' => true]);

Route::middleware('admin_role')->group(function () {
	Route::resource('users', 'UserController', ['names' => 'users']);
	Route::resource('article_categories', 'ArticleCategoryController', ['names' => 'article_categories']);
	Route::resource('push_messages', 'PushMessageController', ['names' => 'push_messages']);
});

Route::middleware('verified','user_role',)->group(function () {
	Route::get('/dashboard', 'UserDashboardController@index')->name('user_dashboard');
	Route::resource('customers', 'CustomerController', ['names' => 'customers']);
	Route::resource('articles', 'ArticleController', ['names' => 'articles']);
	Route::resource('offers', 'OfferController', ['names' => 'offers']);
	Route::resource('invoices', 'InvoiceController', ['names' => 'invoices']);
	Route::resource('user-settings', 'UserSettingsController', ['names' => 'user-settings']);
	Route::resource('offer-invoice-settings', 'OfferInvoiceSettingsController', ['names' => 'offer-invoice-settings']);
	Route::post('get-article-data/{id}','OfferController@getArticleData');
	Route::get('/help', 'UserHelpController@index')->name('help');
});

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    use HasFactory;

    protected $fillable = [
    	'user_id', 'invoice_number', 'customer_id', 'invoice_date',
        'total', 'discount', 'tax', 'tax_value', 'grand_total', 'pdf_file'
    ];

    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    public function customer()
    {
    	return $this->belongsTo('App\Customer');
    }

    public function offer()
    {
        return $this->hasOne('App\Offer');
    }

    public function articles()
    {
    	return $this->hasMany('App\InvoiceArticle');
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Invoice;
use App\User;
use App\Article;
use App\InvoiceArticle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Arr;

class InvoiceController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth');
    }

    public function index()
    {
        $user = User::findOrFail(Auth::user()->id);
        $invoices = $user->invoices;

        return view('invoices.index', compact('invoices'));
    }


    public function create()
    {
        $user = User::findOrFail(Auth::user()->id);
        $customers = $user->customers;
        if(!$customers->count())
            return back()->with('error', __('offers.no_customers'));
        $invoice_number = $this->generateInvoiceNumber($user);
        $articles = Article::all();

        return view('invoices.create', compact('customers', 'invoice_number', 'articles'));
    }

    public function store(Request $request)
    {
    	$user = User::findOrFail(Auth::user()->id);
        $attributes = $this->validateInvoice($current_invoice_number = null, $user);
        $attributes['user_id'] = $user->id;
        $attributes['total'] = 0;
        $attributes['discount'] = 0;
        (request('tax-free-invoice') === 'true') ? 
            $attributes['tax'] = 0 : $attributes['tax'] = 20;
        $attributes['pdf_file'] = 'Invoice_' . time() . '.pdf';

        //Calculate sum for invoice
        $articles = json_decode($attributes['articleslist'], true);
        foreach ($articles as $article) {
            $attributes['total'] += $article['total'];
        }
        $attributes['total'] = number_format((float)$attributes['total'], 2, '.', '');
        $attributes['tax_value'] = ($attributes['total'] * ($attributes['tax']/100));
        $attributes['tax_value'] = number_format((float)$attributes['tax_value'], 2, '.', '');
        $attributes['grand_total'] = $attributes['total'] + $attributes['tax_value'];
        $attributes['grand_total'] = number_format((float)$attributes['grand_total'], 2, '.', '');

        //Create invoice
        $invoice = Invoice::create($attributes);

        //Add fields for articles which are not created automatically
        $articles = collect($articles)->map(function ($item) use($invoice) {
            $item['invoice_id'] = $invoice->id;
            $item['created_at'] = now()->toDateString();
            $item['updated_at'] = now()->toDateString();
            return $item;
        });

        //Insert articles
        InvoiceArticle::insert($articles->toArray());

        //Generate PDF
        $user_settings = $user->user_settings;
        $pdf = PDF::loadView('common.templates.invoice_template1', compact('invoice', 'articles', 'user_settings'));
        //return $pdf->stream();
        $pdf->save(storage_path() .'/app/public/invoices/' . $attributes['pdf_file']);
        
        return redirect ('/invoices')->with('success', __('invoices.invoice_added'));

    }

    public function show(Invoice $invoice)
    {
        abort_if(Gate::denies('update', $invoice), 404);
        if(!Storage::exists('invoices/' . $invoice->pdf_file)) 
            return redirect('/invoices/' . $invoice->id . '/edit')->with('error', __('invoices.pdf_not_found'));

        return response()->file(storage_path() . '/app/public/invoices/' . $invoice->pdf_file);
    }

    public function edit(Invoice $invoice)
    {
        abort_if(Gate::denies('update', $invoice) || !$invoice->customer, 404);
        $customers = Auth::user()->customers;
        $articles = Article::all();
        $invoice_articles = $invoice->articles;
        return view('invoices.edit', compact('invoice', 'customers', 'articles', 'invoice_articles'));
    }

    public function update(Request $request, Invoice $invoice)
    {
    	$user = User::findOrFail(Auth::user()->id);
        $attributes = $this->validateInvoice($current_invoice_number = $invoice->invoice_number, $user);
        $attributes['user_id'] = $user->id;
        $attributes['total'] = 0;
        $attributes['discount'] = 0;
        (request('tax-free-invoice') === 'true') ? 
            $attributes['tax'] = 0 : $attributes['tax'] = 20;
        $attributes['pdf_file'] = 'Invoice_' . time() . '.pdf';

        //Calculate sum for invoice
        $articles = json_decode($attributes['articleslist'], true);
        foreach ($articles as $article) {
            $attributes['total'] += $article['total'];
        }
        $attributes['total'] = number_format((float)$attributes['total'], 2, '.', '');
        $attributes['tax_value'] = ($attributes['total'] * ($attributes['tax']/100));
        $attributes['tax_value'] = number_format((float)$attributes['tax_value'], 2, '.', '');
        $attributes['grand_total'] = $attributes['total'] + $attributes['tax_value'];
        $attributes['grand_total'] = number_format((float)$attributes['grand_total'], 2, '.', '');

        //Add fields for articles which are not created automatically
        $articles = collect($articles)->map(function ($item) use($invoice) {
            $item['invoice_id'] = $invoice->id;
            $item['created_at'] = now()->toDateString();
            $item['updated_at'] = now()->toDateString();
            return $item;
        });

        //Remove all articles for current invoice
        InvoiceArticle::where('invoice_id', $invoice->id)->delete();

        //Remove PDF file
        if(Storage::exists('invoices/' . $invoice->pdf_file))
            Storage::delete('invoices/' . $invoice->pdf_file);

        //Update invoice
        $invoice->update($attributes);

        //Insert new articles
        InvoiceArticle::insert($articles->toArray());

        //Recreate PDF file
        $user_settings = $user->user_settings;
        $pdf = PDF::loadView('common.templates.invoice_template1', compact('invoice', 'articles', 'user_settings'));
        $pdf->save(storage_path() .'/app/public/invoices/' . $attributes['pdf_file']);
        
        return redirect ('/invoices')->with('success', __('invoices.offer_updated'));

    }

    public function destroy(Invoice $invoice)
    {
        abort_if(Gate::denies('update', $invoice), 404);
        $invoice->delete();

        //Remove PDF
        if(Storage::exists('invoices/' . $invoice->pdf_file))
            Storage::delete('invoices/' . $invoice->pdf_file);

        return redirect ('/invoices')->with('success', __('invoices.invoice_deleted'));
    }

    protected function validateinvoice($current_invoice_number, $user)
    {
        $invoice_numbers = '';
        if($user->invoices) {
            $invoice_numbers = $user->invoices->pluck('invoice_number')->toArray();
            if($_SERVER['REQUEST_URI'] != '/invoices') { //edit invoice so we can use existing invoice number as well
                $key = array_search($current_invoice_number, $invoice_numbers);
                $invoice_numbers = Arr::except($invoice_numbers, [$key]);
            }
            $invoice_numbers = implode(',', $invoice_numbers);
        }
        return request()->validate([
            'invoice_number' => ['not_in:'.$invoice_numbers,'required','string','min:8','max:15'],
            'customer_id' => ['required'],
            'invoice_date' => ['required','date'],
            'articleslist' => ['required']
        ]);
    }

    protected function generateInvoiceNumber($user)
    {
        $prefix = ($user->offer_invoice_settings->invoice_prefix) ?? 'RN';
        $delimiter = ($user->offer_invoice_settings->invoice_delimiter) ?? '/';
        $suffix = ($user->offer_invoice_settings->invoice_suffix) ?? date('Y');
        $invoice_numbers = array();

        if($user->invoices) {
            foreach($user->invoices as $invoice) {
            	$temp_number = substr($invoice->invoice_number, 2);
            	$temp_number = substr($temp_number, 0, -5);
                array_push($invoice_numbers, $temp_number);
            }
        }
        if(empty($invoice_numbers))
            return $prefix . '0001' . $delimiter . $suffix;
        else {
            $counter = max($invoice_numbers);
            $counter++;
            switch (true) {
                case $counter < 10: 
                    $number = $prefix . '000' . $counter . $delimiter . $suffix;
                    break;
                case $counter < 100:
                    $number = $prefix . '00' . $counter . $delimiter . $suffix;
                    break;
                case $counter < 1000:
                    $number = $prefix . '0' . $counter . $delimiter . $suffix;
                    break;
                case $counter >= 1000:
                    $number = $prefix . $counter . $delimiter . $suffix;
                    break;
                default:
                    $number = $prefix . rand() . $delimiter . $suffix;
                    break;
            }
            return $number;
        }
    }
}

resources/views/invoices/create.blade.php
@extends('layouts.user')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('invoices.add_invoice')}}</h1>
    </div>
    <div class="container-fluid">
        <form id="invoice-form" action="{{ route('invoices.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="invoice_number">{{ __('invoices.invoice_number')}}</label> 
                        <input type="text" class="form-control @error('invoice_number') is-invalid @enderror" name="invoice_number" value="{{ $invoice_number }}" autofocus>
                        @error('invoice_number')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="customer">{{ __('invoices.customer')}}</label> 
                        <select name="customer_id" class="form-control @error('customer_id') is-invalid @enderror">
                            <option value=""> {{ __('invoices.select_customer')}} </option>
                            @foreach($customers as $customer)   
                                <option type="text" name="customer"
                                    value="{{ $customer->id }}">{{ $customer->company_name ?? $customer->name }}
                                </option>
                            @endforeach
                        </select>
                        @error('customer_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="invoice_date">{{ __('invoices.date')}}</label> 
                        <input id="invoice_date" type="date" class="form-control @error('invoice_date') is-invalid @enderror" name="invoice_date" value="{{ date('Y-m-d') }}" autofocus>
                        @error('invoice_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <input id="articleslist" type="hidden" name="articleslist">
            <input id="tax-free-invoice" type="hidden" name="tax-free-invoice">
        </form>
        <form id="articles-fields">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group form-invoice-inline-elements">
                        <label for="article">{{ __('invoices.article')}}</label>
                        <select id="article_select" name="article_select" class="form-control">
                            <option></option>
                            @foreach($articles as $article)
                                <option class="form-control" name="article" value="{{ $article->id }}" title="{{ $article->price }}">
                                    {{ $article->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-invoice-inline-elements">
                        <label for="price">{{ __('invoices.price')}} €</label> 
                        <input id="price" type="number" class="form-control" name="price" step="0.01" min="0" value="0.00" autofocus>
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="form-group form form-invoice-inline-elements">
                        <label for="quantity">{{ __('invoices.quantity')}}</label> 
                        <input id="quantity" type="number" class="form-control" name="quantity" step="1" min="1" max="10000" value="1" autofocus>
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="form-group form-invoice-inline-elements">
                        <label for="discount">{{ __('invoices.discount')}} %</label> 
                        <input id="discount" type="number" class="form-control" name="discount" step="0.05" min="0.00" max="100" value="0.00" autofocus>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-invoice-inline-elements">
                        <button type="button" class="btn btn-primary add-article">{{ __('buttons.add')}}</button>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-invoice-inline-elements">
                        <button type="button" class="btn btn-primary custom-insert" data-toggle="modal" data-target="#custom-insert-modal">
                            {{ __('buttons.manual_input')}}
                        </button>
                    </div>
                </div>
            </div>
        </form>
        @include('../common/custom-insert-modal')
        @include('../common/edit-modal')
        <div class="row invoice-article-image-preview">
            <div class="col-sm-auto">
                <img id="article-image-preview" src="" width="100px" height="auto">
            </div>
            <div class="col-sm-auto">
                <p id="product_group"></p>
                <p id="price_unit"></p>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table" id="invoice-articles-table" name="articles">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{{ __('invoices.article')}}</th>
                        <th>{{ __('invoices.price')}} €</th>
                        <th>{{ __('invoices.quantity')}}</th>
                        <th>{{ __('invoices.discount')}} %</th>
                        <th>{{ __('invoices.total')}}</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6"></td>
                        <td>
                            <span>{{ __('invoices.total')}}</span>
                            <span id="total">0.00</span>
                            <span>€</span>
                        </td>
                    </tr>
                    <tr class="invoice-tax-total">
                        <td colspan="6"></td>
                        <td>
                            <span>{{ __('invoices.tax')}}</span>
                            <span class="tax-20">20%</span>
                            <span id="tax">0.00</span>
                            <span>€</span>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6"></td>
                        <td>
                            <span>{{ __('invoices.grand_total')}}</span>
                            <span id="grandTotal">0.00</span>
                            <span>€</span>            
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="invoice-buttons">
            <div class="row">
                <div class="col">
                    <input type="checkbox" id="tax-free" name="tax-free"> {{ __('invoices.tax_free_note') }}
                </div>
                <div class="col-auto">
                    <button type="button" class="btn btn-secondary" onclick="window.location.href='{{ route('invoices.index')}}'">
                        {{ __('buttons.back')}}
                    </button>
                    <button id="submit-invoice-button" type="submit" class="btn btn-success btn-save">
                        {{ __('buttons.save')}}
                    </button>
                </div> 
            </div>
        </div>
    </div>
<script src="{{ asset('js/invoiceHelpers.js') }}"></script>

<script>
    $(document).ready(function() {
        $('#article_select').select2({
            placeholder: "{{ __('invoices.select_article') }}",
            theme: "bootstrap4"
        }).on('change', function(){
            var optionPrice = $('option:selected', this).attr('title');
            $('#price').val(optionPrice);
        });
    });
</script>

@endsection

resources/views/invoices/index.blade.php
@extends('layouts.user')

@section('content')
    <div class="mb-3 border-bottom">
        <h1 class="h2">{{ __('invoices.invoices') }}</h1>
    </div>
    <div class="">
        <button type="button" class="btn btn-primary text-nowrap" onclick="location.href='{{ route('invoices.create') }}'" style="float:right; margin-bottom: 0.5em;">
            {{ __('invoices.add_invoice') }}
        </button>
    </div>
    @if(!$invoices->count())
        <p>{{ __('invoices.no_invoices') }}</p>
    @else
        <table id="invoices-table" class="display responsive nowrap" width="100%">
            <thead>
                <tr>
                    <th>{{ __('invoices.invoice_number') }}</th>
                    <th>{{ __('invoices.customer') }}</th>
                    <th>{{ __('invoices.date') }}</th>
                    <th>{{ __('invoices.total') }}</th>
                    <th>{{ __('invoices.discount') }}</th>
                    <th>{{ __('invoices.grand_total') }}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach($invoices as $invoice)
            <tr>
                <td> {{ $invoice->invoice_number }} </td>
                @if($invoice->customer)
                    <td> {{ $invoice->customer->company_name ?? $invoice->customer->name }} </td>
                @else
                    <td> - </td>
                @endif
                <td> {{ $invoice->invoice_date }} </td>
                <td> {{ $invoice->total }} </td>
                <td> {{ $invoice->discount }} </td>
                <td> {{ $invoice->grand_total }} </td>
                <td> 
                    <a href="{{ route('invoices.show', $invoice->id) }}" target="_blank">
                        <span class="feather-icons" data-feather="eye"></span>
                    </a>
                    @if($invoice->customer)
                        <a href="{{ route('invoices.edit', $invoice->id) }}">
                            <span class="feather-icons" data-feather="edit"></span>
                        </a>
                    @endif
                    <a href="#" data-toggle="modal" data-target="#confirm-delete-modal" data-url="{{ route('invoices.destroy', $invoice->id) }}">
                        <span class="feather-icons" data-feather="trash-2"></span>
                    </a>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>
    @endif
    @include('../common/confirm-delete-modal')
    <script>
        $(document).ready( function () {
            var input = {
                stateSave: true,
                responsive: {
                    details: false
                },
                columnDefs: [
                    { responsivePriority: 1, targets: 0 },
                    { responsivePriority: 1, targets: 6 }
                ]
            }; 
            if($('html')[0].lang == 'de') {
                input.language ={url: '/js/localization/dataTables_de.json'};
            }
            $('#invoices-table').DataTable(input);
        });

        $('#confirm-delete-modal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            const url = button.data('url');
            $('#deleteFormClient').attr('action', url);
        });

        $(".alert.alert-success").fadeTo(4000, 500).slideUp(500, function(){
            $(".alert.alert-success").slideUp(500);
        });
    </script>

@endsection