routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('locale/{locale}', function ($locale) {
    session(['locale' =>  $locale]);
    session()->keep('success');   
    return redirect()->back();
});

Route::get('/', function () {
    return redirect('/dashboard');
});

Auth::routes(['verify' => true]);

Route::middleware('admin_role')->group(function () {
	Route::resource('users', 'UserController', ['names' => 'users']);
	Route::resource('article_categories', 'ArticleCategoryController', ['names' => 'article_categories']);
	Route::resource('push_messages', 'PushMessageController', ['names' => 'push_messages']);
});

Route::middleware('verified','user_role',)->group(function () {
	Route::get('/dashboard', 'UserDashboardController@index')->name('user_dashboard');
	Route::resource('customers', 'CustomerController', ['names' => 'customers']);
	Route::resource('articles', 'ArticleController', ['names' => 'articles']);
	Route::resource('offers', 'OfferController', ['names' => 'offers']);
	Route::resource('invoices', 'InvoiceController', ['names' => 'invoices']);
	Route::resource('user-settings', 'UserSettingsController', ['names' => 'user-settings']);
	Route::resource('offer-invoice-settings', 'OfferInvoiceSettingsController', ['names' => 'offer-invoice-settings']);
	Route::post('get-article-data/{id}','OfferController@getArticleData');
	Route::get('/help', 'UserHelpController@index')->name('help');
});

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'InstaOffice') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/sidebar.css') }}" rel="stylesheet">
    <link href="{{ asset('css/overrides.css') }}" rel="stylesheet">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">

</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>InstaOffice</h3>
            </div>
            <ul class="list-unstyled components">
                <li class="nav-item {{ (request()->routeIs('users*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('users.index') }}">
                        <span data-feather="users"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.users') }} </span>
                    </a>
                </li>
                <li class="nav-item {{ (request()->routeIs('article_categories*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('article_categories.index') }}">
                        <span data-feather="list"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.article_categories') }} </span>
                    </a>
                </li>
                <li class="nav-item {{ (request()->routeIs('push_messages*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('push_messages.index') }}">
                        <span data-feather="message-square"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.push_messages') }} </span>
                    </a>
                </li>
            </ul>
        </nav>

        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-info d-md-none">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item text-nowrap">
                                <a class="nav-link" href="{{ route('logout') }}" 
                                    onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                                    {{Auth::user()->email}} [{{ __('topbar.signout') }}]
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
           	<main role="main" class="main-content">
            	@include('flash-message')
                @yield('content')
        	</main>
    	</div>
    </div>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
        feather.replace() //Left nav icons
    </script>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/overrides.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('auth.login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('auth.register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @include('flash-message')
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/user.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'InstaOffice') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <!-- <script src="{{ asset('js/jquery.dataTables.js') }}"></script> -->
    <!-- <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.23/datatables.min.js"></script> -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"> </script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
    <script src="{{ asset('js/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('js/select2.min.js') }}"></script>
    @if(app()->getLocale() == 'de')
        <script src="{{ asset('js/localization/jQueryValidation_de.js') }}"> </script>
    @endif
    <script>
    	$(window).on('load', function(){
		    $('.loading').fadeOut();
		})
    </script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/sidebar.css') }}" rel="stylesheet">
    <!-- <link href="{{ asset('css/jquery.dataTables.css') }}" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.23/datatables.min.css"/>
    <link href="{{ asset('css/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/select2-bootstrap4-min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/overrides.css') }}" rel="stylesheet">

    
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>InstaOffice</h3>
            </div>
            <ul class="list-unstyled components">
                <li class="nav-item {{ (request()->routeIs('user_dashboard*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('user_dashboard') }}">
                        <span data-feather="home"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.dashboard') }} </span>
                    </a>
                </li>
                <li class="nav-item {{ (request()->routeIs('customers*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('customers.index') }}">
                        <span data-feather="users"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.customers') }} </span>
                    </a>
                </li>
                <li class="nav-item {{ (request()->routeIs('articles*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('articles.index') }}">
                        <span data-feather="layers"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.articles') }} </span>
                    </a>
                </li>
                <li class="nav-item {{ (request()->routeIs('offers*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('offers.index') }}">
                        <span data-feather="file-plus"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.offers') }} </span>
                    </a>
                </li>
                <li class="nav-item {{ (request()->routeIs('invoices*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('invoices.index') }}">
                        <span data-feather="file-text"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.invoices') }} </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <span data-feather="settings"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.settings') }} </span>
                    </a>
                    <ul class="collapse list-unstyled {{ (request()->routeIs('user-settings.index') || request()->routeIs('offer-invoice-settings.index')) ? 'show' : '' }}" id="pageSubmenu">
                        <li class="nav-item {{ (request()->routeIs('user-settings.index')) ? 'active' : '' }}">
                            <a href="{{ route('user-settings.index')}}">
                                {{ __('leftnavbar.user-settings') }}
                            </a>
                        </li>
                        <li class="nav-item {{ (request()->routeIs('offer-invoice-settings.index')) ? 'active' : '' }}">
                            <a href="{{ route('offer-invoice-settings.index')}}">
                                {{ __('leftnavbar.offers-invoices') }} 
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item {{ (request()->routeIs('help*')) ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('help') }}">
                        <span data-feather="help-circle"></span>
                        <span class="sidebar-item"> {{ __('leftnavbar.help') }} </span>
                    </a>
                </li>
            </ul>
        </nav>

        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-info d-lg-none">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown user-dropdown">
                                <a id="navbarDropdown" class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('password.request') }}">
                                        <span class="feather-icons" data-feather="refresh-cw"></span> {{ __('topbar.change_password') }}
                                    </a>
                                    <a class="dropdown-item user-logout" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <span class="feather-icons" data-feather="log-out"></span> {{ __('topbar.signout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
           	<main role="main" class="main-content">
                <div class="loading"></div>
            	@include('flash-message')
                @yield('content')
        	</main>
    	</div>
    </div>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
        feather.replace() //Left nav icons
    </script>
</body>
</html>